name: Go

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.23"
          - "1.24"
          - "1.25"
          - "1.26"
    steps:
    - uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
